### ISSUE TITLE
Stackchan_tester.ino コメント：Core2向けスタックチャン基板 X:G19, Y:G27

### ISSUE THREAD

**Issue by uehara00** [mongonta0716/stack-chan-tester#1]
Pan(X)/Tilt(Y)のGPIOアサインですが、本家スタックチャン基板はCore1: G5/G2, Core2: G19/G27と思うのですが、Stackchan_tester.inoのCore2向け冒頭コメントは逆ではないかと思います。
現状：  // スタックチャン基板 X:G27, Y:G19
提案：  // スタックチャン基板 X:G19, Y:G27

**Comment by mongonta0716** [comment]
ご指摘ありがとうございます。

修正しておきます。
